// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Test.proto
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Test.Common {
  public static partial class Broadcaster
  {
    static readonly string __ServiceName = "Test.Common.Broadcaster";

    static readonly grpc::Marshaller<global::Test.Common.ListenerInfo> __Marshaller_ListenerInfo = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Test.Common.ListenerInfo.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Test.Common.Broadcast> __Marshaller_Broadcast = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Test.Common.Broadcast.Parser.ParseFrom);

    static readonly grpc::Method<global::Test.Common.ListenerInfo, global::Test.Common.Broadcast> __Method_Register = new grpc::Method<global::Test.Common.ListenerInfo, global::Test.Common.Broadcast>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "Register",
        __Marshaller_ListenerInfo,
        __Marshaller_Broadcast);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Test.Common.TestReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Broadcaster</summary>
    public abstract partial class BroadcasterBase
    {
      public virtual global::System.Threading.Tasks.Task Register(global::Test.Common.ListenerInfo request, grpc::IServerStreamWriter<global::Test.Common.Broadcast> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Broadcaster</summary>
    public partial class BroadcasterClient : grpc::ClientBase<BroadcasterClient>
    {
      /// <summary>Creates a new client for Broadcaster</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public BroadcasterClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Broadcaster that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public BroadcasterClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected BroadcasterClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected BroadcasterClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::Test.Common.Broadcast> Register(global::Test.Common.ListenerInfo request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Register(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Test.Common.Broadcast> Register(global::Test.Common.ListenerInfo request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_Register, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override BroadcasterClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new BroadcasterClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(BroadcasterBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Register, serviceImpl.Register).Build();
    }

  }
}
#endregion
